# -*- coding: utf-8 -*-
"""LGMVIP-Task-1 .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lWRL2BF9cnFA4QW2ymbUCDIkFdxfd-ws

#LetsGrowMore Internship

# **Author : KAVYA M**

**Task 1 : Exploratory Data Analysis on Terrorism Dataset**
"""

#importing necessary libraries
import pandas as pd
import numpy as np

#importing data
df=pd.read_csv('/content/drive/MyDrive/TSP-GRIP/globalterrorism_data.csv',encoding='latin1')

"""**Exploartory data analysis**"""

df.shape

"""The data contains 181691 rows and 135 columns"""

pd.set_option('display.max_columns',None)
df.head(5)

"""**Handling null values**"""

df.isna().sum().head(20)

na_percent=df.isna().sum()*100/len(df)
pd.set_option('display.max_rows', None)
na_percent.head(150)

"""Removing columns with high null value ratio"""

df2=df[[i for i in df.columns if na_percent[i]<60]]

df2.shape

df2.columns

pd.set_option('display.max_columns',None)
df2.head()

print([i for i in df.columns if na_percent[i]>60])

df3['ransomamt'] = df['ransomamt']
df3['ransompaid'] = df['ransompaid']

"""**Removing unnecessary fields**"""

df3=df2.drop(['eventid','country','region','specificity','vicinity','summary','multiple','crit1','crit2','crit3','doubtterr',\
              'attacktype1','targtype1','targsubtype1','corp1','natlty1','guncertain1','individual','nperpcap','nkillus','nwoundus',\
              'claimed','weaptype1','weapsubtype1','weapsubtype1_txt','weapdetail','property','scite1','scite2',\
              'INT_LOG','INT_IDEO','INT_MISC','INT_ANY'],axis=1)

df3.shape

df3.columns

"""**Renaming columns for better understanding**"""

df4=df3.rename(columns={'iyear':'year','imonth':'month','iday':'day','extended':'duration>24hrs','attacktype1_txt':'attack_type',\
                        'targtype1_txt':'target_type','targsubtype1_txt':'target_subtype','target1':'target',\
                        'natlty1_txt':'nationality_tar','gname':'group_name','npreps':'nterr','weaptype1_txt':'weaptype'})

df4.columns

df4.dtypes

"""**Checking the categorical fields**"""

cat_cols=['duration>24hrs','success','suicide','ishostkid','ransom']
df4[cat_cols].nunique()

pd.unique(df4["ishostkid"])

pd.unique(df4["ransom"])

df4.loc[(df4["ishostkid"] == -9.) | (df4["ransom"] == -9.)]

df4[cat_cols] = df4[cat_cols].replace({0:'No',np.nan:'No',-9.0:'No',1:'Yes'})

df4.loc[(df4["ishostkid"] != 1) & (df4["ishostkid"] != 0)]

df4[cat_cols].nunique()

"""**Saving the cleaned dataset**"""

df4.to_csv('terrorism_data2.csv', index=False)